name: firebase_auth_login_youtube
description: Flutter login ex.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^0.9.8+1
  provider: ^4.0.4
  firebase_auth: ^0.15.5+2
  fluttertoast: ^3.1.3
  english_words: ^3.1.5
  image_picker: ^0.5.3+1
  font_awesome_flutter: ^8.2.0
  firebase_storage: ^3.1.1
  youtube_player_flutter: ^6.0.3+2
  http: ^0.12.0+4
#  kakao_flutter_sdk: ^0.4.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/loading.gif
   - videos/Prologue_Timelapse.mp4
   - assets/icons/singer.png
   - assets/icons/leader.png
   - assets/icons/rev_mic.png
   - assets/icons/eg1.png
   - assets/icons/eg2.png
   - assets/icons/s90es.png
   - assets/icons/motif.png
   - assets/icons/triton.png
   - assets/icons/bass.png
   - assets/icons/ag.png
   - assets/icons/kick.png
   - assets/icons/snare.png
   - assets/icons/hihat.png
   - assets/icons/t1.png
   - assets/icons/t2.png
   - assets/icons/t3.png
   - assets/icons/ohl.png
   - assets/icons/ohr.png
   - assets/xlr_f.png
   - assets/xlr_m.png


#   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: qn
      fonts:
        - asset: fonts/qn_bold.otf
        - asset: fonts/qn_light.otf
        - asset: fonts/qn_medium.otf

  #    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
